import { AgentConfig, AgentName } from "@/types";

export const AGENTS: Record<AgentName, AgentConfig> = {
  SCOUT: {
    id: "SCOUT",
    displayName: "Scout",
    role: "Market Discovery",
    color: "var(--color-agent-scout)",
    bgColor: "var(--color-agent-scout-bg)",
    borderColor: "var(--color-agent-scout-border)",
    initial: "S",
    enabled: true,
  },
  THE_WARDEN: {
    id: "THE_WARDEN",
    displayName: "The Warden",
    role: "Risk & Security",
    color: "var(--color-agent-warden)",
    bgColor: "var(--color-agent-warden-bg)",
    borderColor: "var(--color-agent-warden-border)",
    initial: "W",
    enabled: true,
  },
  LENS: {
    id: "LENS",
    displayName: "Lens",
    role: "Token Intelligence",
    color: "var(--color-agent-lens)",
    bgColor: "var(--color-agent-lens-bg)",
    borderColor: "var(--color-agent-lens-border)",
    initial: "L",
    enabled: true,
  },
  SHADOW: {
    id: "SHADOW",
    displayName: "Shadow",
    role: "Smart Money",
    color: "var(--color-agent-shadow)",
    bgColor: "var(--color-agent-shadow-bg)",
    borderColor: "var(--color-agent-shadow-border)",
    initial: "S",
    enabled: true,
  },
  LEDGER: {
    id: "LEDGER",
    displayName: "Ledger",
    role: "Portfolio Manager",
    color: "var(--color-agent-ledger)",
    bgColor: "var(--color-agent-ledger-bg)",
    borderColor: "var(--color-agent-ledger-border)",
    initial: "L",
    enabled: true,
  },
  PULSE: {
    id: "PULSE",
    displayName: "Pulse",
    role: "Sentiment & Narrative",
    color: "var(--color-agent-pulse)",
    bgColor: "var(--color-agent-pulse-bg)",
    borderColor: "var(--color-agent-pulse-border)",
    initial: "P",
    enabled: true,
  },
  SAGE: {
    id: "SAGE",
    displayName: "Sage",
    role: "Education & Guidance",
    color: "var(--color-agent-sage)",
    bgColor: "var(--color-agent-sage-bg)",
    borderColor: "var(--color-agent-sage-border)",
    initial: "S",
    enabled: true,
  },
  QUILL: {
    id: "QUILL",
    displayName: "Quill",
    role: "Trade Historian",
    color: "var(--color-agent-quill)",
    bgColor: "var(--color-agent-quill-bg)",
    borderColor: "var(--color-agent-quill-border)",
    initial: "Q",
    enabled: true,
  },
  FUTURES: {
    id: "FUTURES",
    displayName: "Futures",
    role: "Derivatives & Leverage",
    color: "var(--color-agent-futures)",
    bgColor: "var(--color-agent-futures-bg)",
    borderColor: "var(--color-agent-futures-border)",
    initial: "F",
    enabled: true,
  },
  BLAZE: {
    id: "BLAZE",
    displayName: "Blaze",
    role: "BSC & BNB Chain",
    color: "var(--color-agent-blaze)",
    bgColor: "var(--color-agent-blaze-bg)",
    borderColor: "var(--color-agent-blaze-border)",
    initial: "B",
    enabled: true,
  },
  THE_ARBITER: {
    id: "THE_ARBITER",
    displayName: "The Arbiter",
    role: "Council Head",
    color: "var(--color-agent-arbiter)",
    bgColor: "var(--color-agent-arbiter-bg)",
    borderColor: "var(--color-agent-arbiter-border)",
    initial: "A",
    enabled: true,
  },
};

export const AGENT_LIST = Object.values(AGENTS);
